### PR TITLE
Data engine OMAS - issue #1831

### PR DESCRIPTION
**Pull request by cong78**
I have no idea why previous PR was failing. I cherry-picked the commits to make a new one now.

### CODE REVIEW

**Comment by cong78** [comment]
I am running a local maven build now to see if there are any failures.

**Review by popa-raluca — APPROVED** [review]

**Comment by popa-raluca** [comment]
> I am running a local maven build now to see if there are any failures.

All good with the build? Is it ok to merge?

**Comment by cong78** [comment]
> > I am running a local maven build now to see if there are any failures.
> 
> All good with the build? Is it ok to merge?

Still running even though I skipped the FVT. 
My laptop is a bit slow now. I will let you know when it is finished.

**Comment by cong78** [comment]
Still running the build. :(

**Comment by popa-raluca** [comment]
> Still running the build. :(

Do you want me to merge it anyway?

**Comment by cong78** [comment]
> > Still running the build. :(
> 
> Do you want me to merge it anyway?

The build just finished and done successfully. 
Go ahead. Thanks

**Pull request merged**
